[build]
builder = "dockerfile"
dockerfilePath = "ecoplanner-be/Dockerfile"
watchPatterns = ["ecoplanner-be/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
